on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the last successful commit
        uses: rarmatei/last-successful-commit-action@latest
        id: last_successful_commit
        with:
          branch: 'main'
      - name: Last successful commit hash
        run: echo "The hash is ${{ steps.last_successful_commit.commit_hash }}"
